---
 general:
   evidence_count: 100
   save_results_with_evidences: True
   es_instance: 'wifo5-33.informatik.uni-mannheim.de'

 query-tables:
    category: null
    path-to-query-table: null
    context-attributes: ['name', 'datePublished']
    target-attributes: ['director']

 pipelines:
    retrieval-strategies:
     -
        name: 'query_by_entity'
     -
        name: 'query_by_goldstandard'

    similarity-re-ranking-strategies:
     -
        name: null
     -
        name: 'huggingface_re_ranker'
        model_name: 'finetuned_cross_encoder-bert-base-uncased-localbusiness_new'
     -
        name: 'magellan_re_ranker'
        model_name: 'RF'


    voting-strategies:
      -
        name: simple
      -
        name: weighted
